# -*- coding: utf-8 -*-
"""Alexis tisseron beauty app (ok to run in streamlight playground)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxuGmWBB11ae6yga5-SVpOiuYTvSxCih
"""

import streamlit as st
import requests
import hashlib
from datetime import datetime, timezone
import json
import pandas as pd # Pour un affichage structuré des résultats

# --- Configuration Globale et Constantes ---

# L'URL API fournie dans info (3).txt
API_BASE_URL = "https://script.google.com/macros/s/AKfycbyNZNOE1DYNbd4GbGTISJsGrnJ4PYCuip0yjSw3Lr8KkD6-kadKI9mfpKNfiAHEWb0Osw/exec"
ALLOWED_MIN, ALLOWED_MAX = 0, 100

# Délais (tirés des scripts commit_client et reveal_client)
# Note: Ces dates sont des exemples fixes pour l'interface utilisateur. En production, l'API devrait les contrôler.
COMMIT_DEADLINE_UTC = datetime(2025, 11, 30, 22, 59, 59, tzinfo=timezone.utc)
REVEAL_OPEN_UTC = datetime(2025, 10, 21, 22, 0, 0, tzinfo=timezone.utc)


# --- Fonctions Utilitaires ---

def sha256(s: str) -> str:
    """Calcule le hash SHA256 d'une chaîne encodée en UTF-8."""
    return hashlib.sha256(s.encode("utf-8")).hexdigest()

def now_utc():
    """Retourne l'heure UTC actuelle."""
    return datetime.now(timezone.utc)

def send_request(kind: str, payload: dict):
    """Envoie une requête POST à l'API."""
    try:
        url = API_BASE_URL
        payload["kind"] = kind # Ajoute le type d'opération (commit ou reveal)

        # Affichage pour le debug
        # st.json(payload)

        r = requests.post(url, json=payload, timeout=15)
        st.session_state.last_response = {"status": r.status_code, "text": r.text}

        if r.status_code == 200:
            try:
                # L'API Google Script renvoie souvent du texte brut ou un JSON simple
                response_data = r.json()
                return True, response_data
            except json.JSONDecodeError:
                return True, {"message": f"Succès (non-JSON): {r.text}"}
        else:
            return False, {"message": f"Erreur API (Code {r.status_code}): {r.text}"}
    except requests.exceptions.Timeout:
        st.session_state.last_response = {"status": "Timeout", "text": "La requête a expiré."}
        return False, {"message": "Erreur réseau: Timeout."}
    except requests.exceptions.RequestException as e:
        st.session_state.last_response = {"status": "Network Error", "text": str(e)}
        return False, {"message": f"Erreur réseau: {e}"}


# --- Logique d'Application ---

def handle_commit(uni_id, number, nonce):
    """Gère l'opération de 'commit'."""
    if not uni_id or not nonce:
        st.error("L'ID Universitaire et le Nonce Secret ne peuvent pas être vides.")
        return

    # Vérification des limites de temps (similaire au script Python)
    current = now_utc()
    if current > COMMIT_DEADLINE_UTC:
        st.error(f"⛔ La fenêtre d'engagement est FERMÉE. (Date limite UTC: {COMMIT_DEADLINE_UTC.isoformat()})")
        return

    preimage = f"{uni_id}|{number}|{nonce}"
    commit_hash = sha256(preimage)

    # Sauvegarde dans la session pour la phase de Reveal
    st.session_state.last_commit_hash = commit_hash
    st.session_state.last_uni_id = uni_id

    payload = {"uni_id": uni_id, "commit": commit_hash}

    success, response = send_request("commit", payload)

    if success:
        st.success("✅ Engagement Soumis avec Succès!")
        st.info(f"Votre **Hash d'Engagement** est : `{commit_hash}`")
        st.warning("⚠️ **GARDEZ CETTE INFORMATION EN SÉCURITÉ** : Vous aurez besoin de votre Numéro et de votre Nonce pour la phase de Révélation (Reveal) !")
        st.session_state.current_page = "result"
        st.rerun()
    else:
        st.error(f"❌ Échec de la soumission de l'engagement : {response.get('message', 'Erreur inconnue')}")


def handle_reveal(uni_id, number, nonce):
    """Gère l'opération de 'reveal'."""
    if not uni_id or not nonce:
        st.error("L'ID Universitaire et le Nonce Secret ne peuvent pas être vides.")
        return

    # Vérification des limites de temps (similaire au script Python)
    current = now_utc()
    if current < REVEAL_OPEN_UTC:
        st.error(f"⛔ La fenêtre de Révélation n'est PAS encore ouverte. (Ouverture UTC: {REVEAL_OPEN_UTC.isoformat()})")
        return

    # Double vérification du hash (côté client)
    preimage_check = f"{uni_id}|{number}|{nonce}"
    commit_check = sha256(preimage_check)

    # Tentative d'envoi à l'API
    payload = {"uni_id": uni_id, "number": number, "nonce": nonce}
    success, response = send_request("reveal", payload)

    if success:
        st.success("🎉 Révélation Soumise avec Succès!")
        st.info(f"Le hash calculé côté client est: `{commit_check}`")
        st.session_state.current_page = "result"
        st.rerun()
    else:
        st.error(f"❌ Échec de la soumission de la révélation : {response.get('message', 'Erreur inconnue')}")
        st.warning("Vérifiez que votre ID, votre Numéro et votre Nonce correspondent EXACTEMENT à ceux que vous avez utilisés lors de l'engagement (Commit)!")


def fetch_results():
    """Tente de récupérer les résultats du leaderboard pour l'affichage."""
    try:
        # Utilisation de l'URL pour les commits et reveals pour simuler l'accès aux données
        leaderboard_url = f"{API_BASE_URL}?table=leaderboard"

        # Pour une meilleure démonstration, nous allons chercher les reveals vérifiés pour l'instant
        reveals_url = f"{API_BASE_URL}?table=reveals"
        r = requests.get(reveals_url, timeout=10)
        r.raise_for_status()

        # Le contenu est supposé être CSV ou un format lisible par pandas
        # Pour l'API Google Script, la réponse est souvent du texte/CSV brut

        # Simulation de la récupération de données CSV (nécessite une conversion)
        # Comme on ne peut pas savoir le format exact renvoyé par le script, on simule
        # un cas où on affiche les données brutes des révélations pour démontrer la connexion.

        if "timestamp" in r.text or "uni_id" in r.text: # Si cela ressemble à des données tabulaires
            data = pd.read_csv(pd.io.common.StringIO(r.text))
            return data
        else:
            st.error(f"Format de données inattendu. Affichage du texte brut: {r.text[:200]}...")
            return None

    except requests.exceptions.RequestException as e:
        st.error(f"Impossible de récupérer les résultats : {e}. Assurez-vous que l'API est configurée pour le leaderboard.")
        return None
    except Exception as e:
        st.error(f"Une erreur s'est produite lors du traitement des résultats: {e}")
        return None


# --- Vues du Frontend Streamlit ---

def view_commit():
    """Interface pour la phase d'Engagement (Commit)."""
    st.header("1. Phase d'Engagement (Commit)")
    st.subheader(f"Date Limite UTC: {COMMIT_DEADLINE_UTC.strftime('%Y-%m-%d %H:%M:%S')}")
    st.markdown("Choisissez votre numéro et un nonce secret. Le hash sera enregistré sur le serveur.")

    with st.form("commit_form"):
        uni_id = st.text_input("Votre ID Universitaire (Ex: A12345)", key="c_uni_id")
        number = st.slider("Votre Numéro (0 à 100)", min_value=ALLOWED_MIN, max_value=ALLOWED_MAX, value=50, step=1, key="c_number")
        nonce = st.text_input("Nonce Secret (un mot/phrase à retenir !)", type="password", key="c_nonce")

        submitted = st.form_submit_button("Soumettre l'Engagement (Commit)")

        if submitted:
            handle_commit(uni_id, number, nonce)


def view_reveal():
    """Interface pour la phase de Révélation (Reveal)."""
    st.header("2. Phase de Révélation (Reveal)")
    st.subheader(f"Ouverture UTC: {REVEAL_OPEN_UTC.strftime('%Y-%m-%d %H:%M:%S')}")
    st.markdown("Entrez les *mêmes* informations que lors du Commit pour révéler votre choix.")

    st.warning("⚠️ ATTENTION : Entrez le Numéro et le Nonce EXACTEMENT tels que vous les avez utilisés lors du Commit.")

    with st.form("reveal_form"):
        uni_id = st.text_input("Votre ID Universitaire (Ex: A12345)", key="r_uni_id",
                               value=st.session_state.get('last_uni_id', ''))
        number = st.number_input("Votre Numéro (0 à 100)", min_value=ALLOWED_MIN, max_value=ALLOWED_MAX, value=50, step=1, key="r_number")
        nonce = st.text_input("Nonce Secret", type="password", key="r_nonce")

        submitted = st.form_submit_button("Soumettre la Révélation (Reveal)")

        if submitted:
            handle_reveal(uni_id, number, nonce)


def view_results():
    """Interface pour l'affichage des résultats."""
    st.header("3. Tableau de Bord et Résultats")
    st.markdown("Cette section affiche les derniers résultats (Commits et Reveals vérifiés).")

    # Affichage de la dernière réponse API pour le debug
    if 'last_response' in st.session_state:
        st.subheader("Dernière Réponse API")
        st.code(st.session_state.last_response.get("text", "N/A"), language='text')

    # Affichage des résultats
    if st.button("Actualiser les Résultats du Leaderboard"):
        data = fetch_results()
        if data is not None:
            st.subheader("Révélations Soumises")
            st.dataframe(data)

    if 'last_commit_hash' in st.session_state:
        st.subheader("Votre Dernier Engagement")
        st.info(f"ID: **{st.session_state.last_uni_id}** | Hash: `{st.session_state.last_commit_hash}`")


# --- Fonction Principale Streamlit ---

def app():
    st.set_page_config(
        page_title="Beauty Contest App",
        layout="centered"
    )

    st.title("⚖️ Concours de Beauté Décentralisé")
    st.markdown("Application de soumission pour le jeu du Concours de Beauté. L'objectif est de choisir un nombre égal aux 2/3 de la moyenne des choix de tous les participants.")

    # Initialisation de l'état de la session
    if 'current_page' not in st.session_state:
        st.session_state.current_page = "commit"
    if 'last_response' not in st.session_state:
        st.session_state.last_response = {}


    # Sélecteur de navigation
    st.sidebar.title("Navigation")
    page = st.sidebar.radio("Aller à", ["Engagement", "Révélation", "Résultats"],
                            index=["commit", "reveal", "result"].index(st.session_state.current_page))

    if page == "Engagement":
        st.session_state.current_page = "commit"
        view_commit()
    elif page == "Révélation":
        st.session_state.current_page = "reveal"
        view_reveal()
    elif page == "Résultats":
        st.session_state.current_page = "result"
        view_results()

    st.sidebar.markdown("---")
    st.sidebar.markdown(f"**URL de l'API:**\n`{API_BASE_URL}`")
    st.sidebar.markdown("_Basé sur les scripts `commit_client` et `reveal_client`_")


if __name__ == "__main__":
    app()